### PR TITLE
fixes from jesstelford

### PR DESCRIPTION
**Pull request by ganlanyuan**
Hey,
This is the fix jesstelford did: https://github.com/keithclark/selectivizr/pull/69. 
I test on my project, it fixed the issues with `@import` and `url`s, that's why I really want it to be added here.

Thanks

### CODE REVIEW

**Comment by corysimmons** [comment]
Thanks, sorry for just now getting to this. Would you mind removing the codekit config and pinging me then I'll merge this?

**Comment by ganlanyuan** [comment]
Could you merge it and then delete the codekit config?
Because the repo has been removed from my side.

**Comment by corysimmons** [comment]
Sure thing.

**Comment by ganlanyuan** [comment]
Thanks

**Comment by corysimmons** [comment]
No problem. The codebase is pretty gnarly spaghetti mess from early 2000's so I'm probably going to revisit this project in the future and only support last jQuery to work with oldIE... just rewrite the entire thing...

**Pull request merged**
